export const FETCHING_USER_PLANTS_START = "FETCHING_USER_PLANTS_START";
export const FETCHING_USER_PLANTS_SUCCESS = "FETCHING_USER_PLANTS_SUCCESS";
export const FETCHING_USER_PLANTS_FAILURE = "FETCHING_USER_PLANTS_FAILURE";

export const getUserPlants = () => async dispatch => {};
